# .github/workflows/build.yml
name: Build & Release Executables

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pyinstaller -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller --onefile gui.py

      - name: Rename binary
        run: |
          mkdir output
          if [ "${{ runner.os }}" == "Windows" ]; then
            mv dist/gui.exe output/superpixel_labeling_tool.exe
          else
            mv dist/gui output/superpixel_labeling_tool-linux
          fi
        shell: bash

      - name: Make Linux binary executable
        if: runner.os == 'Linux'
        run: chmod +x output/superpixel_labeling_tool-linux

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          name: Prebuilt Binaries
          tag_name: latest
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
